hw8
EduardRK/Tinkoff_Java pull request #12
Opened 2023-12-03 20:30 UTC by EduardRK

2023-12-12 15:19 UTC, VictorMinsky requested changes
OK
Жду первую таску и постарайся избавиться от лишнего диффа, который не относится к этой дз

2023-12-12 15:19 UTC, VictorMinsky commented on src/main/java/edu/hw8/Task2/ThreadPool/FixedThreadPool.java
> +public class FixedThreadPool implements ThreadPool {
, AutoCloseable

2023-12-13 16:05 UTC, EduardRK commented on src/main/java/edu/hw8/Task2/ThreadPool/FixedThreadPool.java
> +public class FixedThreadPool implements ThreadPool {
ThreadPool extends AutoCLoseable
Или в любом случае стоит указывать?

2023-12-13 21:20 UTC, VictorMinsky commented on src/main/java/edu/hw8/Task2/ThreadPool/FixedThreadPool.java
> +public class FixedThreadPool implements ThreadPool {
Не заметил, норм тогда

2023-12-13 21:21 UTC, VictorMinsky approved these changes
OK

2023-12-18 10:09 UTC, merged