Add one algorithm of generation and one solver.
EduardRK/Tinkoff_Java pull request #6
Opened 2023-11-05 11:42 UTC by EduardRK

2023-11-21 19:53 UTC, VictorMinsky requested changes

2023-11-21 19:53 UTC, VictorMinsky commented on src/main/java/edu/project2/Cell.java
Настройте правильно ПР
![image](https://github.com/EduardRK/Tinkoff_Java/assets/33966765/1b65e353-313b-4efc-afba-93ecfb415f46)

2023-11-21 19:53 UTC, VictorMinsky commented on src/main/java/edu/project2/Cell.java
У вас неправильно настроен бейдж в README.md файле. Используйте ссылку на свою репу, а не преподавателя

2023-11-21 19:53 UTC, VictorMinsky commented on src/main/java/edu/project2/Generator.java
> +public interface Generator {
Интерфейсы не для того придумывали, чтобы ты в них реализацию писал

2023-11-21 19:53 UTC, VictorMinsky commented on src/main/java/edu/project2/Generator.java
> +        ArrayList<Cell> finalVisitedCells = new ArrayList<>();
Слева интерфейс List

2023-11-21 19:53 UTC, VictorMinsky commented on src/main/java/edu/project2/Generator.java
> +                break;
Используй новый свитч, который через `->` и не требует брейка в каждом кейсе

2023-11-21 19:53 UTC, VictorMinsky commented on src/main/java/edu/project2/Maze.java
> +    private Cell[][] grid;
final

2023-11-21 19:53 UTC, VictorMinsky commented on src/main/java/edu/project2/Maze.java
> +        List<Coordinate> path = new ArrayList<>();
unused

2023-11-21 19:53 UTC, VictorMinsky commented on src/main/java/edu/project2/Maze.java
> +            Cell currentCell = toVisit.remove(0);
`toVisit.removeFirst()`

2023-11-21 19:53 UTC, VictorMinsky commented on src/main/java/edu/project2/Maze.java
> +            int y = currentCell.col();
unused

2023-11-21 19:53 UTC, VictorMinsky commented on src/main/java/edu/project2/Maze.java
> +        maze.append(WALL.repeat(width + 2)).append("\n");
\n это не платформенно-независимый пепренос, используй `System.lineSeparator()`

2023-11-21 19:53 UTC, VictorMinsky commented on src/main/java/edu/project2/Maze.java
> +    }
Методы максимально похожи, вынеси общий код

2023-11-21 19:53 UTC, VictorMinsky commented on src/main/java/edu/project2/Maze.java
> +        return new String(maze);
`return maze.toString();`
Как бы одно и то же (буквально 1 в 1), но всё равно предпочтительнее

2023-11-21 19:53 UTC, VictorMinsky commented on src/main/java/edu/project2/Solver.java
Я правильно понял, что ты у тебя 1 алгоритм генерации и 1 солвер, т. е. ты претендуешь на 8/10?

2023-11-22 07:17 UTC, EduardRK commented on src/main/java/edu/project2/Solver.java
Да, все так. 
Можно немного архитектуру изменить? В то я не совсем понимал, как это все организовать. 
Алгоритмы менять не буду.
Ошибки исправлю.

2023-11-22 07:54 UTC, VictorMinsky commented on src/main/java/edu/project2/Solver.java
Да, можно. Я в принципе не против, если ты еще алгоритмов/солверов докинешь, только отпишись здесь в треде

2023-11-22 07:55 UTC, EduardRK commented on src/main/java/edu/project2/Solver.java
Хорошо.

2023-11-22 16:58 UTC, EduardRK commented on src/main/java/edu/project2/Solver.java
Исправил замечания, добавил еще один решатель MazeSolverDFS.

2023-11-22 18:05 UTC, VictorMinsky commented on src/main/java/edu/project2/Cell.java
Молодец! Ты первый, кто смог правильно настроить бейдж, а не тупо заменил всю ссылку на свою репу)

2023-11-22 18:07 UTC, VictorMinsky approved these changes
OK (+1 решатель, +0 генератор)

2023-11-22 18:26 UTC, merged